## Importando bibliotecas e carregando Datasets

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount("/content/drive")

path = "/content/drive/MyDrive/cdai/ColabNotebooks/xls/"

df_clientes_transacoes = pd.read_excel(path + "dataset_clientes_transacoes.xlsx")
df_produtos = pd.read_excel(path + "dataset_produtos.xlsx")
df_texto = pd.read_excel(path + "dataset_texto.xlsx")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# Análise Exploratória

In [ ]:
df_clientes_transacoes.isnull().values.any()

np.False_

In [ ]:
#cpf nome data_transacao valor
df_clientes_transacoes.info()
# 1230 registros
# 1200 cpf únicos

#id_produto nome categoria   preco
df_produtos.info()
# 1240 observações
# 6 nomes únicos

#frase
df_texto.info()
# 1240 registros
# 6 frases únicas

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1224 entries, 0 to 1223
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   cpf             1224 non-null   int64
 1   nome            1224 non-null   object
 2   data_transacao  1224 non-null   datetime64[ns]
 3   valor           1224 non-null   float64
dtypes: datetime64[ns](1), float64(1), int64(1), object(1)
memory usage: 38.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1230 entries, 0 to 1229
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id_produto  1230 non-null   int64
 1   nome        1230 non-null   object
 2   categoria   1230 non-null   object
 3   preco       1230 non-null   float64
dtypes: float64(1), int64(1), object(2)
memory usage: 38.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1240 entries, 0 to 1239
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   frase   1240 non-null   object
dtypes: object(1)
memory usage: 9.8+ KB

In [ ]:
print("cliente", df_clientes_transacoes["cpf"].nunique())

cliente 1200

# Removendo duplicados

In [ ]:
df_clientes_clean = df_clientes_transacoes.drop_duplicates().copy()
df_produtos_clean = df_produtos.drop_duplicates().copy()
df_texto_clean = df_texto.drop_duplicates().copy()

df_texto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1240 entries, 0 to 1239
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   frase   1240 non-null   object
dtypes: object(1)
memory usage: 9.8+ KB

In [ ]:
pd.set_option("display.max_rows", 500)
df_produtos_clean[df_produtos_clean["categoria"] == "eletronico"]

      id_produto      nome   categoria    preco
0            438  Notebook  eletronico  1218.27
2            356  Notebook  eletronico  4691.80
3            498   Relógio  eletronico  1559.90
4              7   Relógio  eletronico  2355.48
5            359      Fone  eletronico  4435.12
6             92    Camisa  eletronico  3324.89
8            313    Camisa  eletronico  1845.06
10           218   Celular  eletronico   136.37
13           193    Camisa  eletronico   627.62
16           251   Relógio  eletronico   494.94
23            99     Tênis  eletronico   601.39
24           352      Fone  eletronico  4753.73
25           489     Tênis  eletronico  2253.21
27           263     Tênis  eletronico  3511.29
28           500      Fone  eletronico  4001.01
30           487     Tênis  eletronico  1674.87
35           487      Fone  eletronico  2636.66
36           359      Fone  eletronico  2422.38
40           269      Fone  eletronico   773.02
46            43   Relógio  eletronico  2717.02
47           199    Camisa  eletronico  3058.60
48           114      Fone  eletronico  1247.58
49           366   Celular  eletronico  3811.49
51           264    Camisa  eletronico  4921.28
52            10   Celular  eletronico  2643.68
58           368      Fone  eletronico  2670.46
59           309   Celular  eletronico  1045.58
61            62    Camisa  eletronico  2387.69
62           481      Fone  eletronico   987.50
65           240   Celular  eletronico  4240.78
68           481     Tênis  eletronico  4531.63
69           344   Relógio  eletronico  3905.04
71            60   Relógio  eletronico  1932.03
80           205   Relógio  eletronico  4371.83
87            74   Celular  eletronico   334.13
93           240    Camisa  eletronico   344.94
100          269      Fone  eletronico  3871.17
102          133   Relógio  eletronico   927.52
106          460   Relógio  eletronico  2023.64
107          208    Camisa  eletronico  1836.65
109          344   Relógio  eletronico   100.73
113          173    Camisa  eletronico   440.09
119          415   Celular  eletronico  2054.02
121          156     Tênis  eletronico  3808.25
123          107  Notebook  eletronico  4349.94
126          201      Fone  eletronico  4301.55
129          142   Relógio  eletronico  4602.89
132          194     Tênis  eletronico  2224.16
138          222  Notebook  eletronico   426.01
140          401     Tênis  eletronico   349.27
142           33    Camisa  eletronico  2637.40
145          210   Relógio  eletronico  1858.92
150          217  Notebook  eletronico  3482.12
154          473   Celular  eletronico  3187.39
156          185     Tênis  eletronico   275.37
157           15      Fone  eletronico  2753.33
159          223   Relógio  eletronico  2506.97
161          258    Camisa  eletronico    43.61
163          428  Notebook  eletronico  1083.92
168           67      Fone  eletronico  4321.24
170          491   Relógio  eletronico  1808.08
172          425   Celular  eletronico  3094.25
174          159     Tênis  eletronico   555.74
176          137    Camisa  eletronico  1995.47
177          291   Celular  eletronico   418.86
180          297    Camisa  eletronico   328.89
181           84     Tênis  eletronico  2975.28
184          314      Fone  eletronico  3469.76
187           39   Relógio  eletronico  1553.06
188          499  Notebook  eletronico  4932.92
189            2     Tênis  eletronico   890.87
193           64   Celular  eletronico  4831.50
198          229      Fone  eletronico  1084.32
203          143  Notebook  eletronico  1175.65
205          189  Notebook  eletronico  3572.53
208          343   Celular  eletronico  3529.89
209          222    Camisa  eletronico  4292.54
210          124     Tênis  eletronico  2596.49
211          398   Relógio  eletronico  1720.82
212           21   Relógio  eletronico  4887.09
214          260     Tênis  eletronico  4149.17
215          160   Relógio  eletronico  2838.37
217          107     Tênis  eletronico  2680.09
219          360    Camisa  eletronico  4068.13
227          265      Fone  eletronico  1640.46
229           23  Notebook  eletronico  4745.88
230          481  Notebook  eletronico  3542.12
234          456   Relógio  eletronico  3402.01
235          340   Relógio  eletronico  2658.46
242          265    Camisa  eletronico  2359.98
246          171   Celular  eletronico  2737.86
248          166  Notebook  eletronico  2639.77
249          221     Tênis  eletronico   444.48
252          366   Relógio  eletronico  4450.30
253          165      Fone  eletronico  2706.67
254           13   Relógio  eletronico  2523.04
259          179    Camisa  eletronico  2068.20
261          409    Camisa  eletronico  1263.40
262          498   Celular  eletronico  4607.01
264          468    Camisa  eletronico   372.60
270          349   Celular  eletronico  4851.65
272          497   Celular  eletronico  1368.71
274          137   Celular  eletronico  4859.97
280            5      Fone  eletronico   332.06
282          380    Camisa  eletronico   475.09
283          147   Relógio  eletronico   631.23
285          485   Relógio  eletronico   775.10
286          313   Celular  eletronico  1957.28
295          173   Relógio  eletronico   706.59
296          258   Celular  eletronico  1004.55
297            9  Notebook  eletronico  4594.22
303          241   Relógio  eletronico  3209.63
304          426   Celular  eletronico  3043.23
306          327  Notebook  eletronico  3485.93
307          352     Tênis  eletronico  1614.13
308           32  Notebook  eletronico  1985.12
309          109    Camisa  eletronico   767.58
313          326      Fone  eletronico  2116.11
317          413     Tênis  eletronico  4978.65
322          163  Notebook  eletronico  2076.05
342          373      Fone  eletronico  3484.68
349          200    Camisa  eletronico   497.35
351          492  Notebook  eletronico  1792.97
352           95      Fone  eletronico  1445.46
354          263   Celular  eletronico  4485.89
356          370   Relógio  eletronico  4207.87
358          263      Fone  eletronico  2040.59
359          279      Fone  eletronico  1175.70
360          407     Tênis  eletronico  2014.29
366          459  Notebook  eletronico  3493.49
367          416    Camisa  eletronico  3661.26
369          122    Camisa  eletronico  1764.31
372          232   Relógio  eletronico  2909.55
373          209      Fone  eletronico  4059.00
374           36   Relógio  eletronico  2102.25
376           96      Fone  eletronico  1802.71
379          406  Notebook  eletronico   924.78
380          163      Fone  eletronico  1655.54
383            1     Tênis  eletronico  1235.06
386          293      Fone  eletronico  1875.32
391          358   Relógio  eletronico  2573.62
395          161    Camisa  eletronico  2542.73
397          483  Notebook  eletronico  1080.02
398          284     Tênis  eletronico  1795.83
406          270   Celular  eletronico  4433.56
412          189     Tênis  eletronico  2510.60
413          314   Relógio  eletronico  2081.19
418          341    Camisa  eletronico   471.96
419          352    Camisa  eletronico  2655.92
423          337    Camisa  eletronico  4186.89
430          100  Notebook  eletronico  2624.78
431           15  Notebook  eletronico  4133.32
432          431   Celular  eletronico  1133.13
434          328      Fone  eletronico  1540.65
435          256  Notebook  eletronico   850.23
441          366   Celular  eletronico  3153.22
447          125     Tênis  eletronico  2820.72
448          400      Fone  eletronico  3495.49
455          289    Camisa  eletronico  2325.18
458          456   Relógio  eletronico  1950.78
459          221  Notebook  eletronico  2595.44
461            4   Celular  eletronico  1648.69
470          494     Tênis  eletronico   384.80
474          210     Tênis  eletronico    32.80
480          204   Celular  eletronico  2427.44
490          349  Notebook  eletronico  3913.46
491          366   Relógio  eletronico  4674.78
492          188    Camisa  eletronico  1940.42
497          248      Fone  eletronico  2562.88
498          409      Fone  eletronico  3552.80
499          323    Camisa  eletronico  3993.96
517           19     Tênis  eletronico  2294.61
521          471     Tênis  eletronico   220.74
529          313    Camisa  eletronico   483.89
531          218     Tênis  eletronico    58.27
541          441   Relógio  eletronico  3941.47
543          341      Fone  eletronico  4651.93
545           51  Notebook  eletronico  1764.23
547          454      Fone  eletronico   578.38
548          151      Fone  eletronico   792.10
549          376      Fone  eletronico  4711.73
551          232    Camisa  eletronico  4122.49
552          432   Celular  eletronico  2357.26
560          485      Fone  eletronico  1859.27
565          321    Camisa  eletronico  4076.71
567           85   Relógio  eletronico  4694.99
568          274   Relógio  eletronico  2776.48
570          500     Tênis  eletronico  3388.66
574          134   Relógio  eletronico  3693.55
577           27  Notebook  eletronico  3362.40
578          171   Celular  eletronico  3046.82
583          399      Fone  eletronico  2927.92
584          144  Notebook  eletronico  3440.26
585            2   Celular  eletronico  4553.06
589          115     Tênis  eletronico   115.16
590          200    Camisa  eletronico  2634.96
596           76      Fone  eletronico  2280.40
597          181   Relógio  eletronico    76.46
598          159  Notebook  eletronico  4904.28
604          104      Fone  eletronico  1257.04
605          153   Relógio  eletronico   482.74
615          165    Camisa  eletronico  3398.87
620           11  Notebook  eletronico  1124.25
623          292     Tênis  eletronico  1416.00
624          275  Notebook  eletronico  4684.30
625          210     Tênis  eletronico  1447.02
626          109   Relógio  eletronico  2191.79
632          483     Tênis  eletronico  4110.05
634          184  Notebook  eletronico  3011.86
636           39  Notebook  eletronico  1597.68
637          384  Notebook  eletronico  1879.40
638           80     Tênis  eletronico   300.23
641          200      Fone  eletronico  1278.46
642           39   Relógio  eletronico   724.36
646          193      Fone  eletronico  2687.70
648            3      Fone  eletronico   318.70
653          385   Relógio  eletronico  4784.74
661          126  Notebook  eletronico  3866.70
666          390   Celular  eletronico  2645.34
668          181     Tênis  eletronico   970.94
669          382    Camisa  eletronico  4932.07
670          292      Fone  eletronico  4779.02
672          372      Fone  eletronico    84.91
673           81    Camisa  eletronico  3358.38
675           13  Notebook  eletronico  4998.50
677          424    Camisa  eletronico  3399.97
679           65  Notebook  eletronico   908.59
691          442   Relógio  eletronico    97.27
694          146   Celular  eletronico  1660.37
695          149   Relógio  eletronico  1642.07
696           46    Camisa  eletronico  3394.71
700           80  Notebook  eletronico  3608.29
703          180   Celular  eletronico   924.58
704          344   Relógio  eletronico  4889.97
709          226    Camisa  eletronico  3129.91
710          374   Relógio  eletronico   325.11
713          429    Camisa  eletronico  3767.99
719            8     Tênis  eletronico   180.89
721          358    Camisa  eletronico   203.48
723          234      Fone  eletronico  4510.89
728          452   Relógio  eletronico  4670.44
729          260  Notebook  eletronico  3006.09
734          487      Fone  eletronico    92.17
735           69    Camisa  eletronico  1197.20
736          131      Fone  eletronico  3547.80
744           97    Camisa  eletronico  1484.92
746            4  Notebook  eletronico  2161.32
747          152   Relógio  eletronico   459.59
750           79   Celular  eletronico  1258.63
753           16      Fone  eletronico   748.07
754          286   Celular  eletronico  3814.80
755          336   Relógio  eletronico  1424.58
756           78     Tênis  eletronico  2813.89
757          341   Relógio  eletronico  4778.35
761          151    Camisa  eletronico   108.27
763          120   Celular  eletronico  3354.07
765           71     Tênis  eletronico   340.27
773          318  Notebook  eletronico   915.42
775          336   Relógio  eletronico   127.15
776          291     Tênis  eletronico  2983.72
781           64  Notebook  eletronico  2907.17
782          190  Notebook  eletronico   488.38
784            9    Camisa  eletronico  2116.43
785          496      Fone  eletronico  2676.81
796          206     Tênis  eletronico  2123.70
802           77   Celular  eletronico  4420.71
803          230    Camisa  eletronico  1262.42
815          460   Relógio  eletronico  1032.96
817          119  Notebook  eletronico   341.14
820          178   Celular  eletronico   305.77
823          418  Notebook  eletronico  1849.68
825            7  Notebook  eletronico   165.90
833          243     Tênis  eletronico  3430.77
838           31   Celular  eletronico  3160.48
841          442   Celular  eletronico  3430.56
842          105  Notebook  eletronico   914.05
843           24    Camisa  eletronico  4574.11
844          375      Fone  eletronico  2177.41
850          319     Tênis  eletronico  2031.77
854          186    Camisa  eletronico  3954.25
855          160     Tênis  eletronico  3329.05
856          351   Relógio  eletronico  1209.23
857          198  Notebook  eletronico  3791.92
858          336   Relógio  eletronico  4133.35
863           20   Relógio  eletronico   264.30
872          468  Notebook  eletronico  1246.98
873          403     Tênis  eletronico  3506.57
875          378     Tênis  eletronico  2782.10
876          411   Celular  eletronico  2332.86
877          363     Tênis  eletronico  3966.87
881          125      Fone  eletronico  1274.18
883           10  Notebook  eletronico  3779.16
890          307   Celular  eletronico  3327.60
896          287      Fone  eletronico  2512.62
904          474  Notebook  eletronico  4038.29
905           78      Fone  eletronico  1069.74
906          444   Relógio  eletronico   242.37
907          219    Camisa  eletronico  3799.67
909          462    Camisa  eletronico  1694.16
910          226     Tênis  eletronico  4005.27
911           83  Notebook  eletronico   545.45
916          498     Tênis  eletronico  3335.21
917           34     Tênis  eletronico  1100.02
919          106   Relógio  eletronico  1064.38
922           90   Celular  eletronico  1795.03
925           37  Notebook  eletronico  3227.56
926           46   Relógio  eletronico  1427.52
927          151     Tênis  eletronico  3775.26
930          155     Tênis  eletronico  3294.87
931          484   Celular  eletronico   138.22
932           93      Fone  eletronico  1712.05
934          207  Notebook  eletronico  2149.04
937           47      Fone  eletronico  2940.23
939          282    Camisa  eletronico  3641.41
941           96   Celular  eletronico    52.61
942          276   Celular  eletronico    21.31
943          170  Notebook  eletronico   646.27
945          155     Tênis  eletronico   743.73
946           85      Fone  eletronico  1735.46
947           23  Notebook  eletronico  1112.28
948          324  Notebook  eletronico  3328.29
958           57   Relógio  eletronico  1967.18
959          336  Notebook  eletronico  2650.48
960          265     Tênis  eletronico  4628.50
967          343     Tênis  eletronico  1175.93
969           52     Tênis  eletronico  2705.55
971           82    Camisa  eletronico   252.23
976          483     Tênis  eletronico  1380.40
984          406  Notebook  eletronico  3263.77
989          425      Fone  eletronico  1894.09
990          485   Celular  eletronico  4302.38
991          200    Camisa  eletronico  3902.39
995          379     Tênis  eletronico  2777.50
999          421   Celular  eletronico  2235.38
1004         110   Celular  eletronico  1932.12
1007         360   Relógio  eletronico  2953.24
1016         247      Fone  eletronico   551.35
1017          58  Notebook  eletronico  3466.76
1021         474     Tênis  eletronico  2280.53
1023         131   Relógio  eletronico  4518.21
1024         393     Tênis  eletronico  1723.32
1034         447      Fone  eletronico  2677.55
1036         319   Relógio  eletronico  1325.65
1042         126    Camisa  eletronico  2130.55
1045         178   Celular  eletronico  1071.41
1047          86      Fone  eletronico  1213.99
1050         286      Fone  eletronico  2780.58
1051         398      Fone  eletronico  2276.00
1052         324    Camisa  eletronico  4946.41
1054         450    Camisa  eletronico   754.67
1055         496   Celular  eletronico  3861.26
1059         343    Camisa  eletronico  4571.47
1063         202  Notebook  eletronico  2080.96
1064          76      Fone  eletronico  4023.81
1065          82   Celular  eletronico   466.81
1070         382    Camisa  eletronico   750.15
1072         352      Fone  eletronico   980.86
1077          24     Tênis  eletronico  2067.50
1079         248  Notebook  eletronico  3473.17
1088         220  Notebook  eletronico  3929.10
1090         162   Celular  eletronico  4608.17
1091         104    Camisa  eletronico  3971.14
1093         409   Relógio  eletronico   892.33
1095         374  Notebook  eletronico  3414.75
1101         111      Fone  eletronico  3988.18
1102         259   Relógio  eletronico   307.19
1103         484      Fone  eletronico  4732.60
1104         227     Tênis  eletronico   190.64
1115         346      Fone  eletronico  1257.21
1116         391    Camisa  eletronico  3925.82
1119         323    Camisa  eletronico  2379.95
1126          73  Notebook  eletronico  1286.01
1130         440    Camisa  eletronico  3238.35
1139         127     Tênis  eletronico   858.22
1142         401  Notebook  eletronico  3547.69
1147         264      Fone  eletronico  2098.69
1158         344   Celular  eletronico  1848.90
1160         231   Relógio  eletronico   122.80
1161         255   Celular  eletronico  3426.42
1165          37   Relógio  eletronico  3412.62
1167         218      Fone  eletronico  3646.89
1172         251   Celular  eletronico  4441.07
1173         332      Fone  eletronico  4491.26
1174          40    Camisa  eletronico   176.43
1180         412    Camisa  eletronico  1914.72
1186          59      Fone  eletronico  2950.88
1188         338     Tênis  eletronico  1925.92
1193         498   Celular  eletronico  2596.85
1199         232      Fone  eletronico  3907.81
1200         289    Camisa  eletronico  2446.70
1201         306   Celular  eletronico  3295.60
1204         488    Camisa  eletronico  4669.91
1210         278    Camisa  eletronico  3215.66
1212         293   Relógio  eletronico  4499.68
1213         147     Tênis  eletronico  4099.53
1216         431   Relógio  eletronico  3337.67
1224         131    Camisa  eletronico  4890.33
1226          97   Relógio  eletronico   527.59

In [ ]:
with pd.option_context("display.max_rows", 200):
    display(df_produtos_clean.sort_values(by="id_produto"))

     id_produto      nome   categoria    preco
239           1    Camisa       roupa   353.85
383           1     Tênis  eletronico  1235.06
22            1  Notebook       roupa  2075.11
585           2   Celular  eletronico  4553.06
189           2     Tênis  eletronico   890.87
..          ...       ...         ...      ...
188         499  Notebook  eletronico  4932.92
337         499      Fone       roupa   199.36
570         500     Tênis  eletronico  3388.66
99          500   Celular   acessorio  4215.19
28          500      Fone  eletronico  4001.01

[1200 rows x 4 columns]

In [ ]:
display(df_produtos_clean.sample(1000))

      id_produto      nome   categoria    preco
773          318  Notebook  eletronico   915.42
94           409   Celular   acessorio  4903.73
398          284     Tênis  eletronico  1795.83
813          329   Relógio   acessorio    53.28
3            498   Relógio  eletronico  1559.90
...          ...       ...         ...      ...
549          376      Fone  eletronico  4711.73
317          413     Tênis  eletronico  4978.65
1226          97   Relógio  eletronico   527.59
537          122  Notebook       roupa  3629.94
309          109    Camisa  eletronico   767.58

[1000 rows x 4 columns]

# Ajustes nos dados

In [ ]:
correct_products_category = {
    "Notebook" : "Eletrônico",
    "Relógio": "Acessório",
    "Fone": "Eletrônico",
    "Camisa": "Roupa",
    "Celular": "Eletrônico",
    "Tênis": "Acessório",
}

df_produtos_clean["categoria"] = df_produtos_clean["nome"].map(correct_products_category).fillna(df_produtos_clean["categoria"])
df_produtos_clean.sample(15)

      id_produto      nome   categoria    preco
369          122    Camisa       Roupa  1764.31
456          167  Notebook  Eletrônico   777.86
860          352     Tênis   Acessório  4572.70
382          244  Notebook  Eletrônico  3054.03
936          303   Relógio   Acessório  3880.39
546           42   Relógio   Acessório  3889.56
970          188   Celular  Eletrônico  2259.20
750           79   Celular  Eletrônico  1258.63
801          324   Relógio   Acessório   725.81
990          485   Celular  Eletrônico  4302.38
168           67      Fone  Eletrônico  4321.24
188          499  Notebook  Eletrônico  4932.92
235          340   Relógio   Acessório  2658.46
538          222     Tênis   Acessório  3771.83
1006         232      Fone  Eletrônico  3521.95

In [ ]:

print(df_produtos_clean["categoria"].unique())
display(df_produtos_clean.sample(5))

['Eletrônico' 'Acessório' 'Roupa']

      id_produto      nome   categoria    preco
1218         109   Celular  Eletrônico  1719.56
254           13   Relógio   Acessório  2523.04
310          465   Relógio   Acessório  2824.37
604          104      Fone  Eletrônico  1257.04
244          408  Notebook  Eletrônico   257.28

In [ ]:
df_produtos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1230 entries, 0 to 1229
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id_produto  1230 non-null   int64
 1   nome        1230 non-null   object
 2   categoria   1230 non-null   object
 3   preco       1230 non-null   float64
dtypes: float64(1), int64(1), object(2)
memory usage: 38.6+ KB

In [ ]:
with pd.option_context("display.max_rows", 1300):
    display(df_produtos_clean.sort_values(by="id_produto"))

      id_produto      nome   categoria    preco
239            1    Camisa       Roupa   353.85
383            1     Tênis   Acessório  1235.06
22             1  Notebook  Eletrônico  2075.11
585            2   Celular  Eletrônico  4553.06
189            2     Tênis   Acessório   890.87
1078           3  Notebook  Eletrônico  4373.04
327            3      Fone  Eletrônico  3901.89
557            3   Relógio   Acessório  2374.49
648            3      Fone  Eletrônico   318.70
746            4  Notebook  Eletrônico  2161.32
81             4     Tênis   Acessório  2573.92
461            4   Celular  Eletrônico  1648.69
280            5      Fone  Eletrônico   332.06
399            7      Fone  Eletrônico  1261.89
4              7   Relógio   Acessório  2355.48
1049           7   Relógio   Acessório  4478.46
964            7  Notebook  Eletrônico  4954.25
50             7   Celular  Eletrônico  3676.51
825            7  Notebook  Eletrônico   165.90
719            8     Tênis   Acessório   180.89
1083           8     Tênis   Acessório  4405.95
417            8   Celular  Eletrônico  3355.02
689            9      Fone  Eletrônico  1638.17
784            9    Camisa       Roupa  2116.43
479            9      Fone  Eletrônico  2941.88
569            9   Celular  Eletrônico    81.25
297            9  Notebook  Eletrônico  4594.22
883           10  Notebook  Eletrônico  3779.16
832           10   Celular  Eletrônico  2579.61
52            10   Celular  Eletrônico  2643.68
994           11    Camisa       Roupa  4433.01
289           11   Relógio   Acessório  4027.07
620           11  Notebook  Eletrônico  1124.25
866           12   Relógio   Acessório  3758.70
675           13  Notebook  Eletrônico  4998.50
693           13     Tênis   Acessório   580.95
469           13   Relógio   Acessório  1637.28
254           13   Relógio   Acessório  2523.04
157           15      Fone  Eletrônico  2753.33
1030          15     Tênis   Acessório   244.08
431           15  Notebook  Eletrônico  4133.32
690           15     Tênis   Acessório  3702.02
715           16   Celular  Eletrônico  1708.93
753           16      Fone  Eletrônico   748.07
701           16   Celular  Eletrônico  3906.31
111           16      Fone  Eletrônico  2363.60
54            16   Relógio   Acessório   861.31
77            16  Notebook  Eletrônico  1550.51
256           17    Camisa       Roupa  1508.06
400           18   Celular  Eletrônico  4481.34
699           18      Fone  Eletrônico   109.24
1229          18    Camisa       Roupa  1216.02
517           19     Tênis   Acessório  2294.61
863           20   Relógio   Acessório   264.30
347           20     Tênis   Acessório   123.98
563           20  Notebook  Eletrônico   497.06
743           20   Relógio   Acessório   109.60
962           21   Celular  Eletrônico  1467.51
212           21   Relógio   Acessório  4887.09
770           21  Notebook  Eletrônico   199.87
220           21    Camisa       Roupa  4237.64
619           22    Camisa       Roupa    95.96
298           22   Relógio   Acessório  4524.06
171           22    Camisa       Roupa  3528.47
229           23  Notebook  Eletrônico  4745.88
947           23  Notebook  Eletrônico  1112.28
1029          23      Fone  Eletrônico   446.45
116           23   Relógio   Acessório  3322.36
324           23   Relógio   Acessório   255.14
528           23   Relógio   Acessório   149.59
843           24    Camisa       Roupa  4574.11
378           24   Celular  Eletrônico   125.54
885           24     Tênis   Acessório  4439.97
793           24   Relógio   Acessório  1463.76
1077          24     Tênis   Acessório  2067.50
183           25      Fone  Eletrônico  4279.04
645           27   Relógio   Acessório  1719.43
577           27  Notebook  Eletrônico  3362.40
1062          28  Notebook  Eletrônico  4365.48
1066          28   Relógio   Acessório  4871.85
797           30    Camisa       Roupa  2351.49
786           30   Relógio   Acessório   226.64
475           31      Fone  Eletrônico  3969.68
838           31   Celular  Eletrônico  3160.48
1127          31   Relógio   Acessório  2922.38
308           32  Notebook  Eletrônico  1985.12
142           33    Camisa       Roupa  2637.40
316           33   Celular  Eletrônico  2077.20
917           34     Tênis   Acessório  1100.02
1035          35     Tênis   Acessório  2647.89
591           35   Celular  Eletrônico  1634.48
1170          36      Fone  Eletrônico  2230.53
86            36  Notebook  Eletrônico  2805.04
374           36   Relógio   Acessório  2102.25
925           37  Notebook  Eletrônico  3227.56
1165          37   Relógio   Acessório  3412.62
267           38   Relógio   Acessório  1761.33
1227          38   Celular  Eletrônico  2931.91
642           39   Relógio   Acessório   724.36
187           39   Relógio   Acessório  1553.06
11            39      Fone  Eletrônico  3548.24
636           39  Notebook  Eletrônico  1597.68
789           40   Relógio   Acessório   717.53
1174          40    Camisa       Roupa   176.43
544           40  Notebook  Eletrônico  1567.64
935           40   Celular  Eletrônico  2554.03
506           41  Notebook  Eletrônico  2173.12
667           41   Celular  Eletrônico   553.05
120           41    Camisa       Roupa  3528.44
546           42   Relógio   Acessório  3889.56
408           42     Tênis   Acessório  2675.92
46            43   Relógio   Acessório  2717.02
519           44   Celular  Eletrônico  2448.49
790           44    Camisa       Roupa  1124.11
1105          44      Fone  Eletrônico  4202.29
1205          44    Camisa       Roupa  4632.91
345           45   Relógio   Acessório  4412.28
696           46    Camisa       Roupa  3394.71
926           46   Relógio   Acessório  1427.52
1005          46     Tênis   Acessório  4794.64
290           46    Camisa       Roupa  4028.67
845           46     Tênis   Acessório  2874.99
732           46      Fone  Eletrônico   794.48
7             47   Relógio   Acessório   364.38
135           47   Celular  Eletrônico  1667.22
937           47      Fone  Eletrônico  2940.23
436           48     Tênis   Acessório  4505.90
512           49   Celular  Eletrônico  3793.67
522           49  Notebook  Eletrônico  1239.06
524           51     Tênis   Acessório  3021.19
545           51  Notebook  Eletrônico  1764.23
1208          51  Notebook  Eletrônico   564.31
404           52   Relógio   Acessório  2075.82
969           52     Tênis   Acessório  2705.55
819           53  Notebook  Eletrônico  2024.72
1128          53   Relógio   Acessório   441.58
1025          54   Relógio   Acessório  3141.86
1179          54    Camisa       Roupa  3957.61
986           55   Celular  Eletrônico   423.72
467           55  Notebook  Eletrônico  2151.84
1185          55  Notebook  Eletrônico  2785.24
1080          57      Fone  Eletrônico  3190.39
362           57   Relógio   Acessório  1338.65
446           57      Fone  Eletrônico  2177.63
553           57      Fone  Eletrônico   652.31
91            57     Tênis   Acessório  2764.58
336           57  Notebook  Eletrônico  1759.77
958           57   Relógio   Acessório  1967.18
1219          58     Tênis   Acessório   832.36
1017          58  Notebook  Eletrônico  3466.76
1186          59      Fone  Eletrônico  2950.88
1157          60  Notebook  Eletrônico  4020.05
136           60    Camisa       Roupa   168.12
71            60   Relógio   Acessório  1932.03
523           60     Tênis   Acessório  1075.14
1033          62    Camisa       Roupa   170.43
61            62    Camisa       Roupa  2387.69
231           63   Relógio   Acessório  1857.08
276           63   Relógio   Acessório  2752.62
649           63   Celular  Eletrônico  3538.28
1211          63   Relógio   Acessório  1352.24
167           64      Fone  Eletrônico  4655.29
193           64   Celular  Eletrônico  4831.50
781           64  Notebook  Eletrônico  2907.17
588           64      Fone  Eletrônico   985.41
1008          65  Notebook  Eletrônico   371.19
571           65   Relógio   Acessório  4359.82
679           65  Notebook  Eletrônico   908.59
848           66     Tênis   Acessório   165.56
168           67      Fone  Eletrônico  4321.24
952           67   Celular  Eletrônico   769.90
963           67      Fone  Eletrônico  4510.08
536           68      Fone  Eletrônico  3585.14
424           68  Notebook  Eletrônico  3559.52
671           68     Tênis   Acessório  3174.19
1085          69   Relógio   Acessório   899.79
735           69    Camisa       Roupa  1197.20
21            70  Notebook  Eletrônico  2944.27
902           70    Camisa       Roupa   600.23
748           71    Camisa       Roupa    52.03
765           71     Tênis   Acessório   340.27
711           72  Notebook  Eletrônico   710.36
38            72     Tênis   Acessório  2154.29
738           72   Relógio   Acessório  2785.60
829           73  Notebook  Eletrônico  4934.03
213           73   Relógio   Acessório  1314.18
1126          73  Notebook  Eletrônico  1286.01
76            73      Fone  Eletrônico  4864.52
977           73  Notebook  Eletrônico  2591.00
87            74   Celular  Eletrônico   334.13
271           74  Notebook  Eletrônico  4981.22
403           75  Notebook  Eletrônico  2710.87
712           75  Notebook  Eletrônico  3958.85
1064          76      Fone  Eletrônico  4023.81
596           76      Fone  Eletrônico  2280.40
151           76  Notebook  Eletrônico  4069.39
908           77   Relógio   Acessório  4199.87
1020          77      Fone  Eletrônico  1969.63
361           77   Relógio   Acessório  2173.43
265           77    Camisa       Roupa  1869.04
802           77   Celular  Eletrônico  4420.71
1031          77     Tênis   Acessório  1536.03
559           77   Celular  Eletrônico  3418.20
1117          78    Camisa       Roupa  4360.87
420           78  Notebook  Eletrônico  1246.73
905           78      Fone  Eletrônico  1069.74
756           78     Tênis   Acessório  2813.89
1087          79    Camisa       Roupa  1777.06
816           79     Tênis   Acessório  1152.26
750           79   Celular  Eletrônico  1258.63
502           79      Fone  Eletrônico   974.74
638           80     Tênis   Acessório   300.23
700           80  Notebook  Eletrônico  3608.29
41            80   Celular  Eletrônico  3879.58
402           80      Fone  Eletrônico  2629.94
673           81    Camisa       Roupa  3358.38
1123          81   Celular  Eletrônico   583.82
1065          82   Celular  Eletrônico   466.81
971           82    Camisa       Roupa   252.23
1058          82     Tênis   Acessório  3737.56
973           82     Tênis   Acessório  2337.38
678           82   Celular  Eletrônico  2892.60
439           82     Tênis   Acessório  1362.67
911           83  Notebook  Eletrônico   545.45
299           83     Tênis   Acessório  2517.42
1010          83   Celular  Eletrônico  4295.00
1209          83      Fone  Eletrônico  2872.65
993           83  Notebook  Eletrônico  3086.82
181           84     Tênis   Acessório  2975.28
1192          84      Fone  Eletrônico  2723.83
415           84      Fone  Eletrônico  3905.27
564           85    Camisa       Roupa   101.28
567           85   Relógio   Acessório  4694.99
946           85      Fone  Eletrônico  1735.46
1047          86      Fone  Eletrônico  1213.99
489           86  Notebook  Eletrônico  4476.70
9             90      Fone  Eletrônico  1887.37
922           90   Celular  Eletrônico  1795.03
392           91    Camisa       Roupa  4837.34
1125          92    Camisa       Roupa  3415.17
6             92    Camisa       Roupa  3324.89
932           93      Fone  Eletrônico  1712.05
726           93      Fone  Eletrônico  4473.76
635           93     Tênis   Acessório  3073.11
771           94   Celular  Eletrônico  1515.74
352           95      Fone  Eletrônico  1445.46
941           96   Celular  Eletrônico    52.61
1028          96    Camisa       Roupa  4975.53
376           96      Fone  Eletrônico  1802.71
822           96     Tênis   Acessório  4051.76
1226          97   Relógio   Acessório   527.59
744           97    Camisa       Roupa  1484.92
742           97   Celular  Eletrônico  1854.11
847           98   Relógio   Acessório  4397.69
928           98    Camisa       Roupa  2957.06
511           99   Celular  Eletrônico  2301.08
23            99     Tênis   Acessório   601.39
1225          99  Notebook  Eletrônico  3041.52
430          100  Notebook  Eletrônico  2624.78
1221         100   Celular  Eletrônico  4445.80
407          101      Fone  Eletrônico  4606.38
478          101   Relógio   Acessório  1948.85
269          103  Notebook  Eletrônico  1566.81
14           104     Tênis   Acessório  2469.22
1091         104    Camisa       Roupa  3971.14
1057         104    Camisa       Roupa  3746.56
604          104      Fone  Eletrônico  1257.04
987          104  Notebook  Eletrônico   975.12
842          105  Notebook  Eletrônico   914.05
919          106   Relógio   Acessório  1064.38
85           106   Relógio   Acessório  4594.36
217          107     Tênis   Acessório  2680.09
123          107  Notebook  Eletrônico  4349.94
1120         108   Relógio   Acessório  3854.69
626          109   Relógio   Acessório  2191.79
1218         109   Celular  Eletrônico  1719.56
309          109    Camisa       Roupa   767.58
1137         109   Relógio   Acessório  1978.80
64           110  Notebook  Eletrônico  2959.85
1004         110   Celular  Eletrônico  1932.12
1101         111      Fone  Eletrônico  3988.18
428          112   Celular  Eletrônico  4639.15
224          113      Fone  Eletrônico  1637.20
384          113     Tênis   Acessório  2765.82
48           114      Fone  Eletrônico  1247.58
706          114   Celular  Eletrônico  3165.84
647          114      Fone  Eletrônico   974.73
117          114      Fone  Eletrônico  3081.19
589          115     Tênis   Acessório   115.16
853          115    Camisa       Roupa  3521.17
255          117  Notebook  Eletrônico  4182.45
527          118   Relógio   Acessório  1496.58
56           118  Notebook  Eletrônico   829.02
137          118  Notebook  Eletrônico  3385.10
817          119  Notebook  Eletrônico   341.14
763          120   Celular  Eletrônico  3354.07
245          121   Celular  Eletrônico  1879.34
1001         121      Fone  Eletrônico  3395.10
457          121      Fone  Eletrônico  1772.31
465          121     Tênis   Acessório   308.78
884          121   Celular  Eletrônico  1477.27
644          122   Relógio   Acessório  1925.02
314          122   Celular  Eletrônico  1390.50
315          122   Relógio   Acessório   850.90
369          122    Camisa       Roupa  1764.31
537          122  Notebook  Eletrônico  3629.94
1177         122      Fone  Eletrônico  2468.20
365          123     Tênis   Acessório   389.96
63           123      Fone  Eletrônico  4581.74
592          123  Notebook  Eletrônico  4213.10
207          124      Fone  Eletrônico  3050.24
631          124    Camisa       Roupa   723.50
210          124     Tênis   Acessório  2596.49
302          125  Notebook  Eletrônico   676.31
447          125     Tênis   Acessório  2820.72
881          125      Fone  Eletrônico  1274.18
1042         126    Camisa       Roupa  2130.55
661          126  Notebook  Eletrônico  3866.70
1198         126      Fone  Eletrônico   304.19
899          127  Notebook  Eletrônico  1469.52
422          127   Celular  Eletrônico  4119.66
1139         127     Tênis   Acessório   858.22
888          127   Celular  Eletrônico  4152.64
809          127     Tênis   Acessório  4559.36
622          128    Camisa       Roupa  3663.98
257          128   Relógio   Acessório  1397.81
250          130      Fone  Eletrônico  1230.20
146          130     Tênis   Acessório  1307.24
1169         130   Celular  Eletrônico   561.64
1156         131   Celular  Eletrônico  2525.05
1023         131   Relógio   Acessório  4518.21
1224         131    Camisa       Roupa  4890.33
736          131      Fone  Eletrônico  3547.80
102          133   Relógio   Acessório   927.52
674          133    Camisa       Roupa  2200.34
191          134     Tênis   Acessório  4565.90
1184         134     Tênis   Acessório  1898.92
574          134   Relógio   Acessório  3693.55
766          135      Fone  Eletrônico  3643.53
55           136   Relógio   Acessório  4145.14
607          136     Tênis   Acessório  3745.50
810          137    Camisa       Roupa  3358.93
692          137   Celular  Eletrônico  3708.17
274          137   Celular  Eletrônico  4859.97
176          137    Camisa       Roupa  1995.47
697          138    Camisa       Roupa  4404.29
949          138      Fone  Eletrônico  1970.92
292          139   Celular  Eletrônico  2946.42
1171         140   Celular  Eletrônico  3857.80
504          142    Camisa       Roupa  3703.13
90           142      Fone  Eletrônico  1781.41
129          142   Relógio   Acessório  4602.89
203          143  Notebook  Eletrônico  1175.65
323          143  Notebook  Eletrônico  2446.78
814          143      Fone  Eletrônico   196.99
584          144  Notebook  Eletrônico  3440.26
443          145  Notebook  Eletrônico  4656.12
481          145      Fone  Eletrônico   150.55
694          146   Celular  Eletrônico  1660.37
483          147   Celular  Eletrônico   731.28
283          147   Relógio   Acessório   631.23
1213         147     Tênis   Acessório  4099.53
216          148      Fone  Eletrônico  3951.90
695          149   Relógio   Acessório  1642.07
745          149    Camisa       Roupa  2617.23
733          149   Celular  Eletrônico  4155.37
685          149   Celular  Eletrônico  1422.05
869          150    Camisa       Roupa  4768.95
927          151     Tênis   Acessório  3775.26
761          151    Camisa       Roupa   108.27
548          151      Fone  Eletrônico   792.10
294          151     Tênis   Acessório   120.46
747          152   Relógio   Acessório   459.59
92           152      Fone  Eletrônico  2408.60
840          152   Relógio   Acessório    26.90
605          153   Relógio   Acessório   482.74
794          154   Celular  Eletrônico  4774.93
1164         154  Notebook  Eletrônico  1028.44
1140         154   Relógio   Acessório  2691.70
131          154    Camisa       Roupa  3124.21
82           154     Tênis   Acessório  3898.19
29           154    Camisa       Roupa  4698.27
930          155     Tênis   Acessório  3294.87
945          155     Tênis   Acessório   743.73
121          156     Tênis   Acessório  3808.25
19           157  Notebook  Eletrônico  3612.47
795          157   Relógio   Acessório  4546.54
831          158     Tênis   Acessório  1229.94
1181         158     Tênis   Acessório  2612.60
174          159     Tênis   Acessório   555.74
598          159  Notebook  Eletrônico  4904.28
215          160   Relógio   Acessório  2838.37
759          160    Camisa       Roupa  4127.12
855          160     Tênis   Acessório  3329.05
363          160      Fone  Eletrônico  3706.10
1131         161  Notebook  Eletrônico    31.59
395          161    Camisa       Roupa  2542.73
618          161   Celular  Eletrônico  1011.55
355          161   Relógio   Acessório  4892.60
134          161  Notebook  Eletrônico    99.18
1075         161      Fone  Eletrônico   436.07
226          161   Celular  Eletrônico  2226.30
1176         162    Camisa       Roupa  3311.12
687          162    Camisa       Roupa  4187.57
1090         162   Celular  Eletrônico  4608.17
664          162  Notebook  Eletrônico   886.64
640          162    Camisa       Roupa  3475.36
1082         163   Relógio   Acessório  4061.90
301          163      Fone  Eletrônico  4911.23
380          163      Fone  Eletrônico  1655.54
322          163  Notebook  Eletrônico  2076.05
339          164      Fone  Eletrônico   652.20
133          164  Notebook  Eletrônico  4715.98
1019         164  Notebook  Eletrônico  2694.72
166          164  Notebook  Eletrônico   767.67

In [ ]:
print("nome", df_produtos_clean["id_produto"].nunique())

nome 446

# Solução Hashtable

In [ ]:
products = [[] for _ in range(len(df_produtos))]

def hash_function(value):
  if not isinstance(value, str):
    value = str(value)
  sum_of_chars = 0
  for char in value:
    sum_of_chars += ord(char)
  return sum_of_chars % len(products)

def add(product_details):
  index = hash_function(product_details["nome"])
  products[index].append(product_details)

def contains(product_name):
  index = hash_function(product_name)
  for product_detail_dict in products[index]:
    if product_detail_dict["nome"] == product_name:
      return True
  return False

def get(product_name):
  index = hash_function(product_name)
  found_products = []
  for product_detail_dict in products[index]:
    if product_detail_dict["nome"] == product_name:
      found_products.append(product_detail_dict)
  return found_products if found_products else None


for i in range(len(products)):
    products[i].clear()

for index, row in df_produtos_clean.iterrows():
    product_data = {
        "nome": row["nome"],
        "categoria": row["categoria"],
        "preco": row["preco"]
    }
    add(product_data)

# Outra ideia de implementação Hash

Transformando as variáveis em Hash, adicionando em uma lista, depois utilizando o Hash para buscar o produto

In [ ]:
def generate_hashcode(text):
  return __builtins__.hash(str(text))


def find_product(the_list, value):
  found = []
  for i in the_list:
    if str(i[0]) == value:
      found.append(i)
  return found


products_hash = []

for index, row in df_produtos_clean.drop_duplicates(subset=['nome']).iterrows():
  product_name = row["nome"]
  hash_code = generate_hashcode(product_name)
  product = [hash_code, product_name, row["categoria"], row["preco"]]
  products_hash.append(product)



find_product(products_hash, "-90331920082656692")

[[-90331920082656692, 'Relógio', 'Acessório', 1559.9]]

# Solução com dicionário

Dicionários tem comportamento de hashtable no Python.

Possui ID e não duplica ID
Criei um dicionário de produtos, dessa forma consigo diferenciar produtos que tem ID duplicado, porém são produtos diferentes.

A colisão é tratada ao dar um ID diferente para cada linha

In [ ]:
ht_products = {}

for index, row in df_produtos_clean.iterrows():
    id_master = index
    product_details = {
        "id" : row["id_produto"],
        "name": row["nome"],
        "category": row["categoria"],
        "price": row["preco"]
    }
    ht_products[id_master] = product_details


for i, a in ht_products.items():
  if a["id"] == 438:
    print(i, a)

#df_produtos_clean[df_produtos_clean["id_produto"] == 438]

0 {'id': 438, 'name': 'Notebook', 'category': 'Eletrônico', 'price': 1218.27}
258 {'id': 438, 'name': 'Tênis', 'category': 'Acessório', 'price': 3701.83}

In [ ]:
my_list = [
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  []
]

def hash_function(value):
  sum_of_chars = 0
  for char in value:
    sum_of_chars += ord(char)

  return sum_of_chars % 10


def add(name):
  index = hash_function(name)
  my_list[index].append(name)


def contains(name):
  index = hash_function(name)
  return my_list[index] == name

In [ ]:
df_clientes_clean

              cpf     nome data_transacao   valor
0     24637532215     João     2024-02-02   68.24
2     23708816826    Lucas     2024-08-31   93.05
3     48591453407     João     2024-04-11   91.40
4     91022689701     João     2024-11-10  308.02
5     23325709421    Maria     2024-03-23  182.60
...           ...      ...            ...     ...
1219  61177652754    Maria     2024-08-30  467.49
1220  49008468393      Ana     2024-06-05  291.59
1221  42497455828  Beatriz     2024-12-07  298.22
1222  46459516831     João     2024-07-16  472.32
1223  81636787855  Beatriz     2024-12-11  146.96

[1200 rows x 4 columns]

# Parquet

In [ ]:
df_produtos_clean.to_parquet(path + "produtos.parquet", index=False)

# Library

Tentando implementar uma Biblioteca.

Com funções para criar Hash, Listar, Excluir

In [ ]:
class Node:
    def __init__(self, key, value):
        self.key = key
        self.value = value
        self.next = None


class HashTableLibrary:
    def __init__(self, capacity):
        if capacity <= 0:
            raise ValueError(">0")
        self.capacity = capacity
        self.size = 0
        self.table = [None] * capacity

    def _hash(self, key):
        if not isinstance(key, str):
            key = str(key)
        sum_of_chars = 0
        for char in key:
            sum_of_chars += ord(char)
        return sum_of_chars % self.capacity

    def add(self, key, value):
        index = self._hash(key)

        if self.table[index] is None:
            self.table[index] = Node(key, value)
            self.size += 1
        else:
            current = self.table[index]
            while current:
                if current.key == key:
                    current.value = value
                    return
                if current.next is None:
                    current.next = Node(key, value)
                    self.size += 1
                    return
                current = current.next


    def get(self, key):
        index = self._hash(key)
        found_values = []

        current = self.table[index]
        while current:
            if current.key == key:
                found_values.append(current.value)
            current = current.next

        if not found_values:
            raise KeyError("")
        return found_values


    def remove(self, key):
        index = self._hash(key)

        previous = None
        current = self.table[index]
        removed_count = 0

        while current:
            if current.key == key:
                if previous:
                    previous.next = current.next
                else:
                    self.table[index] = current.next
                self.size -= 1
                removed_count += 1
                current = self.table[index] if not previous else previous.next
            else:
                previous = current
                current = current.next

        if removed_count == 0:
            raise KeyError("")


    def __len__(self):
        return self.size

    def __contains__(self, key):
        try:
            self.get(key)
            return True
        except KeyError:
            return False

    def display(self):
        for i, bucket in enumerate(self.table):
            if bucket:
                print(f"Bucket {i}:")
                current = bucket
                while current:
                    print(f"{current.key} {current.value}")
                    current = current.next
            else:
                print(f"Empty")

hash_table_capacity = len(df_produtos_clean.drop_duplicates(subset=["nome"])) * 2
product_hash_table = HashTableLibrary(hash_table_capacity)

print(f"capacity: {product_hash_table.capacity}")

for index, row in df_produtos_clean.iterrows():
    product_data = {
        "id_produto": row["id_produto"],
        "nome": row["nome"],
        "categoria": row["categoria"],
        "preco": row["preco"]
    }
    product_hash_table.add(row["nome"], product_data)

example_name_exists = df_produtos_clean.iloc[0]["nome"]
try:
    retrieved_products = product_hash_table.get(example_name_exists)
    print(f"Retrieved {example_name_exists}: {retrieved_products}")
except KeyError as e:
    print(e)


collision_test_name = "Camisa"
try:
    retrieved_products_collision = product_hash_table.get(collision_test_name)
    print(f"Retrieved all {collision_test_name} entries (demonstrating collision handling): {retrieved_products_collision}")
except KeyError as e:
    print(e)


name_to_remove = "Camisa"
try:
    product_hash_table.remove(name_to_remove)
    print(f"Current size after removal: {len(product_hash_table)}")
    try:
        print(f"Attempt to get {name_to_remove} after removal: {product_hash_table.get(name_to_remove)}")
    except KeyError as e:
        print(f"As expected {name_to_remove} not found after removal: {e}")
except KeyError as e:
    print(e)

capacity: 12
Retrieved Notebook: [{'id_produto': 99, 'nome': 'Notebook', 'categoria': 'Eletrônico', 'preco': 3041.52}]
Retrieved all Camisa entries (demonstrating collision handling): [{'id_produto': 18, 'nome': 'Camisa', 'categoria': 'Roupa', 'preco': 1216.02}]
Current size after removal: 5
As expected Camisa not found after removal: ''